quantAPP/views.py
from flask_login import login_required
from flask import render_template
from flask import flash, redirect, render_template, url_for
from flask_login import login_required, login_user, logout_user
from flask import Blueprint
from .forms import LoginForm, RegistrationForm
from . import db
from .models import Employee


auth_blueprint = Blueprint('auth', __name__)


@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    Handle requests to the /register route
    Add an employee to the database through the registration form
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        employee = Employee(email=form.email.data,
                            username=form.username.data,
                            first_name=form.first_name.data,
                            last_name=form.last_name.data,
                            password=form.password.data)

        # add employee to the database
        db.session.add(employee)
        db.session.commit()
        flash('You have successfully registered! You may now login.')

        # redirect to the login page
        return redirect(url_for('auth.login'))

    # load registration template
    return render_template('auth/register.html', form=form, title='Register')


@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Handle requests to the /login route
    Log an employee in through the login form
    """
    form = LoginForm()
    if form.validate_on_submit():

        # check whether employee exists in the database and whether
        # the password entered matches the password in the database
        employee = Employee.query.filter_by(email=form.email.data).first()
        if employee is not None and employee.verify_password(
                form.password.data):
            # log employee in
            login_user(employee)

            # redirect to the dashboard page after login
            return redirect(url_for('home.dashboard'))

        # when login details are incorrect
        else:
            flash('Invalid email or password.')

    # load login template
    return render_template('auth/login.html', form=form, title='Login')


@auth_blueprint.route('/logout')
@login_required
def logout():
    """
    Handle requests to the /logout route
    Log an employee out through the logout link
    """
    logout_user()
    flash('You have successfully been logged out.')

    # redirect to the login page
    return redirect(url_for('auth.login'))


# app/home/views.py


home_blueprint = Blueprint('home', __name__)


@home_blueprint.route('/home')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home_blueprint.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")


admin_blueprint = Blueprint('admin', __name__)

quantAPP/templates/components/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/sidebar.css">
    <link rel="stylesheet" href="/static/css/navbar.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/cards.css">
    <link rel="stylesheet" href="/static/css/charts.css">
    <link rel="stylesheet" href="/static/css/form_login.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <!-- Font Awesome JS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="shortcut icon" href="/static/img/logo.png" />
    {% block page_head %}{% endblock %}
    <title>{{title}}</title>
</head>

<body>

    <div class="wrapper">
        {% include 'components/sidebar.html' %}

        <!-- Page Content  -->
        <div id="content">
            {% include 'components/navbar.html' %}
            <div id="page_header">
                {% block page_body %}{% endblock %}
            </div>
            <div id="footer">
                {% include 'components/footer.html' %}
            </div>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <script src="/static/js/main.js"></script>

</body>

</html>

quantAPP/templates/components/cards.html
<div id="content-cards">
    <h3>Dashboard</h3>
</div>
<br>


<!-- Main content cards -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{ibov['day']}}</h3>
                        <h4>{{ibov['daily']}}%</h4>
                        <p>Ibovespa</p>
                    </div>
                    <div class="icon">
                        <a href="/ibov_update" class="small-box-footer">Atualizar</a> <i
                            class="fas fa-cloud-download-alt"></i></a>
                    </div>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{sp500['day']}}</h3>
                        <h4>{{sp500['daily']}}%</h4>
                        <p>S&P 500</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                        <a href="/sp500_update" class="small-box-footer">Atualizar<i
                                class="fas fa-cloud-download-alt"></i></a>
                    </div>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>{{dol['day']}}</h3>
                        <h4>{{dol['daily']}}%</h4>
                        <p>USD/BRL</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                        <a href="/dol_update" class="small-box-footer">Atualizar<i
                                class="fas fa-cloud-download-alt"></i></a>
                    </div>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{ifix['day']}}</h3>
                        <h4>{{ifix['daily']}}%</h4>
                        <p>IFIX</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                        <a href="/ifix_update" class="small-box-footer">Atualizar<i
                                class="fas fa-cloud-download-alt"></i></a>
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
    </div>
</section>

quantAPP/templates/components/column_charts.html
<!-- <br>
<section class="content">
    <div class="container-fluid">
        <div id="columnchart_material" style="width: 800px; height: 500px;"></div>
    </div>
</section> -->



<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['bar']});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Período', 'Ibovespa', 'S&P 500', "Dolar", 'Ifix'],
      ['Diário', {{ibov['daily']}}, {{sp500['daily']}}, {{dol['daily']}}, {{ifix['daily']}}],
      ['Semanal', {{ibov['weekly']}}, {{sp500['weekly']}}, {{dol['weekly']}}, {{ifix['weekly']}}],
      ['Mensal', {{ibov['monthly']}}, {{sp500['monthly']}}, {{dol['monthly']}}, {{ifix['monthly']}}],
      ['12 Meses', {{ibov['twelve_months']}}, {{sp500['twelve_months']}}, {{dol['twelve_months']}}, {{ifix['twelve_months']}}],
      ['No Ano', {{ibov['annual']}}, {{sp500['annual']}}, {{dol['annual']}}, {{ifix['annual']}}]
    ]);
    var options = {
        width: 1600,
        height: 400,
        vAxis:   {format: "#.##'%'"},
      chart: {
        title: 'Performance dos Índice',
      }, 
    };
    var chart = new google.charts.Bar(document.getElementById('columnchart_material'));
    chart.draw(data, google.charts.Bar.convertOptions(options));
  }
</script>

quantAPP/templates/components/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Conecte-se conosco nas redes sociais!</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i> Bootstrap investment
                    </h6>
                    <p>
                        Trabalho de Conclusão de Curso apresentado à Universidade Virtual do Estado de São Paulo, como parte dos requisitos
                        necessários à obtenção do título de Bacharel, no Curso de Engenharia de Computação.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Alunos
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Weslei</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Allyson</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Juliana</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Eduardo</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Denys</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Links úteis 
                    </h6>
                    <p>
                        <a href="https://www.b3.com.br/pt_br/" class="text-reset">Bolsa de Valores (B3)</a>
                    </p>
                    <p>
                        <a href="https://cei.b3.com.br/CEI_Responsivo/" class="text-reset">Canal Eletrônico do Investidor (CEI)</a>
                    </p>
                    <p>
                        <a href="https://www.bcb.gov.br/" class="text-reset">banco central do brasil</a>
                    </p>
                    <p>
                        <a href="https://www.gov.br/cvm/pt-br" class="text-reset">Comissão de Valores Mobiliários (CVM)</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Universidade</h6>
                    <p><i class="fas fa-home me-3"></i> Univesp</p>
                    <p><i class="fas fa-envelope me-3"></i> atendimento@univesp.br</p>
                    <p><i class="fas fa-phone me-3"></i> (11) 3188-6700</p>
                    <p><i class="fas fa-print me-3"></i> 0800 051 3333</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="#">Grupo 041</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

quantAPP/templates/components/line_charts.html
<!-- <div id="line_top_x"></div> -->


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['line'] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'últimos 12 meses');
        data.addColumn('number', 'Ibovespa');
        data.addColumn('number', 'S&P500');
        data.addColumn('number', 'Dolar');
        data.addColumn('number', 'Ifix');

        data.addRows([
{%for key in ind%}
['{{key}}', {{ind[key]}}, {{sp[key]}}, {{ wdo[key]}}, {{ ifix0[key]}}],
{% endfor %}
        ]);
        var options = {
            chart: {
                title: 'Performance dos Índice',
            },
            width: 1600,
            height: 400,
        };
        var chart = new google.charts.Line(document.getElementById('line_top_x'));
        chart.draw(data, google.charts.Line.convertOptions(options));
    }
</script>

quantAPP/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>
            <span>Toggle</span>
        </button>

        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>



        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('dashboard_blueprint.dashboard') }}">Dashboard</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link"><i class="far fa-user"></i>   {{current_user.username }}</a>
                </li>
                {% else %}
                <li class="nav-item active">
                <a class="nav-link" href="{{url_for('home.homepage')}}">Home</a>
                </li>
                <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

quantAPP/templates/components/pie_charts.html
<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    var options = {
        chartArea: { width: '95%', height: '80%' },
        title: "Distribuição da carteira de Ações",
        // width: 790,
        height: 300,
        bar: { groupWidth: "95%" },
        pieHole: 0.4,
        legend: { position: "center" },
    };

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ["Element", "Quantidade", { role: "style" }],
            {% for wallet, info, stock_value in zip(wallet_user[0], wallet_user[1], wallet_user[2]) %}
    {% if wallet.classe == "AÇÃO" %}
    ["{{info.shortName}}", {{ wallet.amount * stock_value }}, 'color: #76A7FA'],
        {% endif %}
    {% endfor %}  
                
            ]);
    var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
    chart.draw(data, options);
    }

    google.charts.setOnLoadCallback(drawChart2);
    function drawChart2() {
        var data = google.visualization.arrayToDataTable([
            ["Element", "Quantidade", { role: "style" }],
            {% for wallet_user, info, stock_value in zip(wallet_user[0], wallet_user[1], wallet_user[2]) %}
    {% if wallet_user.classe == "FII" %}
    ["{{info.shortName}}", {{ wallet_user.amount * stock_value }}, 'color: #76A7FA'],
        {% endif %}
    {% endfor %}  
                
            ]);
    options['title'] = "Distribuição da carteira de FIIs"
    var chart2 = new google.visualization.PieChart(document.getElementById('donutchart2'));
    chart2.draw(data, options);
    }

    google.charts.setOnLoadCallback(drawChart3);
    function drawChart3() {
        var data = google.visualization.arrayToDataTable([
            ["Element", "Quantidade", { role: "style" }],
            {% for wallet, info, stock_value in zip(wallet_user[0], wallet_user[1], wallet_user[2]) %}
    {% if wallet.classe == "BDR" %}
    ["{{info.shortName}}", {{ wallet.amount * stock_value }}, 'color: #76A7FA'],
        {% endif %}
    {% endfor %}  
                
            ]);
    options['title'] = "Distribuição da carteira de BDRs"
    var chart3 = new google.visualization.PieChart(document.getElementById('donutchart3'));
    chart3.draw(data, options);
    }

    google.charts.setOnLoadCallback(drawChart4);
    function drawChart4() {
        var data = google.visualization.arrayToDataTable([
            ["Element", "Quantidade", { role: "style" }],
            {% for wallet, info, stock_value in zip(wallet_user[0], wallet_user[1], wallet_user[2]) %}
    {% if wallet.classe == "ETF" %}
    ["{{info.shortName}}", {{ wallet.amount * stock_value }}, 'color: #76A7FA'],
        {% endif %}
    {% endfor %}  
                
            ]);
    options['title'] = "Distribuição da carteira de ETFs"
    var chart4 = new google.visualization.PieChart(document.getElementById('donutchart4'));
    chart4.draw(data, options);
    }

    google.charts.setOnLoadCallback(drawChart5);
    function drawChart5() {
        var data = google.visualization.arrayToDataTable([
            ["Element", "Quantidade", { role: "style" }],
            {%for x in wallet %}
    ["{{x}}", {{ wallet[x]}}, 'color: #76A7FA'],
        {% endfor %}  
                
            ]);
    options['title'] = "Distribuição da carteira Geral"
    var chart5 = new google.visualization.PieChart(document.getElementById('donutchart5'));
    chart5.draw(data, options);
    }

</script>

quantAPP/templates/components/sidebar.html
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <a href="{{ url_for('home.homepage') }}">
        <h4><i class="fas fa-poll" style="color:#F39571"></i> Bootstrap <b>Investment</b></h4>
        </a>
        <strong><i class="fas fa-poll"></i></strong>
    </div>

    <ul class="list-unstyled components">
        <li>
            <a href="{{url_for('home.homepage')}}">
                <i class="fas fa-home"></i>
                Home
            </a>
        </li>
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="fas fa-wallet"></i> Assets
            </a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="{{url_for('home.homepage')}}">Home 1</a>
                </li>
                <li>
                    <a href="#">Home 2</a>
                </li>
                <li>
                    <a href="#">Home 3</a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#">
                <i class="fas fa-briefcase"></i>
                About
            </a>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="fas fa-copy"></i>
                Pages
            </a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="#">Page 1</a>
                </li>
                <li>
                    <a href="#">Page 2</a>
                </li>
                <li>
                    <a href="#">Page 3</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">
                <i class="fas fa-image"></i>
                Portfolio
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fas fa-cog"></i>
                Tools
            </a>
        </li>


        <li>
            <a href="#">
                <i class="fas fa-question"></i>
                FAQ
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fas fa-paper-plane"></i>
                Contact
            </a>
        </li>
    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
        </li>
        <li>
            <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
        </li>
    </ul>
</nav>