quantAPP/ext/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    IntegerField,
    StringField,
    FloatField,
    SelectField,
    SubmitField,
    DateTimeField,
)
from wtforms.validators import InputRequired, ValidationError


def validate_ticket(form, field):
    if len(field.data) > 6:
        raise ValidationError("O ticket não é valido")


class WalletForm(FlaskForm):
    ticket = StringField("Ticket", validators=[InputRequired(), validate_ticket])
    kind = SelectField(
        "Tipo", choices=["Compra", "Venda"], validators=[InputRequired()]
    )
    date = DateTimeField("Data", validators=[InputRequired()])
    amount = IntegerField("Quantidade", validators=[InputRequired()])
    price = FloatField("Preço", validators=[InputRequired()])
    classe = SelectField(
        "Classe", choices=["AÇÃO", "BDR", "FII", "ETF"], validators=[InputRequired()]
    )
    submit = SubmitField("Adicionar")

quantAPP/ext/dashboard/views.py
from flask_login import login_required, current_user
from flask import Blueprint, render_template, flash, redirect, url_for
from quantAPP.ext.profit.profit import stock, info
from quantAPP.ext.db.models import Wallet
from quantAPP.ext.db import db
from .forms import WalletForm
import matplotlib.pyplot as plt
from base64 import b64encode
import io

dashboard_blueprint = Blueprint("dashboard_blueprint", __name__)


@dashboard_blueprint.route("/dashboard/", methods=["GET", "POST"])
@dashboard_blueprint.route("/dashboard/<ticket>", methods=["GET", "POST"])
@login_required
def dashboard(ticket=None):
    if ticket:
        return render_template(
            "dashboard/details.html",
            title="Detalhe",
            id=id,
            ticket=ticket,
            stock=info(ticket),
            graphic=plot(ticket),
        )
    else:
        return render_template(
            "dashboard/dashboard.html",
            title="Dashboard",
            wallet_user=query_table(),
            zip=zip,
            wallet=query_wallet_distribution(),
        )


@dashboard_blueprint.route("/dashboard/add_position", methods=["GET", "POST"])
@login_required
def add_position():
    form = WalletForm()
    if form.validate_on_submit():
        position = Wallet(
            ticket=form.ticket.data,
            kind=form.kind.data,
            date=form.date.data,
            amount=form.amount.data,
            price=form.price.data,
            classe=form.classe.data,
            users_id=current_user.get_id(),
        )
        db.session.add(position)
        db.session.commit()
        flash("Posição adicionada com sucesso!")
        info(form.ticket.data)
        return redirect(url_for("dashboard_blueprint.dashboard"))

    return render_template(
        "dashboard/wallet_form.html",
        form=form,
        title="Adicionar Posição",
    )


def plot(ticket):
    df = stock(ticket)["Close"]
    plt.figure()
    df.plot()
    buf = io.BytesIO()
    plt.savefig(buf, format="png")
    buf.seek(0)
    buffer = b"".join(buf)
    graphic = b64encode(buffer).decode("utf-8")
    return graphic


def query_table():
    stmt = f"""
        SELECT 
            id,
            ticket,
            kind,
            condition,
            date,
            sum(w.amount) as amount,
            sum(w.price)/COUNT(w.ticket) as price,
            classe,
            users_id
        from wallets w
            where w.users_id == {current_user.id}
            and w.condition == 'Open'
        group by w.ticket
    """
    query = [
        {column: value for column, value in rowproxy.items()}
        for rowproxy in db.session.execute(stmt).fetchall()
    ]

    query_info = [info(stock["ticket"]).to_dict("records")[0] for stock in query]

    query_stock_value = [
        round(float(stock(ticket["ticket"]).tail(1)["Close"]), 2) for ticket in query
    ]

    return query, query_info, query_stock_value


def query_wallet_distribution():
    wallet = {
        "FII": 0,
        "BDR": 0,
        "ETF": 0,
        "AÇÃO": 0,
    }
    table = query_table()
    for stock_value, classe in zip(table[2], table[0]):
        wallet[classe["classe"]] += classe["amount"] * stock_value
    return wallet

quantAPP/templates/dashboard/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "components/base.html" %}
{% block page_body %}
{% include 'components/pie_charts.html' %}
{{ utils.flashed_messages() }}
<h1>Dashboard</h1>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div id="donutchart"></div>
            </div>
            <div class="col-sm">
                <div id="donutchart3"></div>
            </div>
            <div class="col-sm">
                <div id="donutchart4"></div>
            </div>

            <div class="col-sm">
                <div id="donutchart2"></div>
            </div>
        </div>
    </div>
</section>
<br>
<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Ticket</th>
            <th scope="col">Tipo</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Preço médio</th>
            <th scope="col">Preço atual</th>
            <th scope="col">Valor de mercado</th>
            <th scope="col">P/L</th>
            <th scope="col">%P/L</th>
        </tr>
    </thead>
    <tbody>
        {% for wallet, info, stock_value in zip(wallet_user[0], wallet_user[1], wallet_user[2])%}
        <tr>
            <th scope="row">{{loop.index}}</th>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{info.shortName}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{wallet.ticket|upper}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{wallet.kind}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{wallet.amount}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{"R$ {:,.2f}".format(wallet.price)}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{"R$ {:,.2f}".format(stock_value)}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{"R$ {:,.2f}".format(wallet.amount * stock_value)}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{"R$ {:,.2f}".format((wallet.amount * stock_value)-(wallet.price*wallet.amount))}}</a></td>
            <td><a href="{{url_for('dashboard_blueprint.dashboard')}}{{wallet.ticket}}">{{"{:,.2f}%".format(((wallet.amount * stock_value)/(wallet.price*wallet.amount)-1)*100)}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="col">
    <a type="button" class="btn btn-info  float-right" href="{{url_for('dashboard_blueprint.add_position')}}">
        <span>Add Posição</span>
    </a>
</div>
<br>
<br>
<br>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div id="donutchart5"></div>
            </div>
        </div>
    </div>
</section>

<br><br><br><br><br>

{% endblock %}

quantAPP/templates/dashboard/details.html
{% extends "components/base.html" %}
{% block page_body %}

<div class="content-section">
    <div class="datails ml-4">
        <h1>{{stock.shortName.to_string(index=False)}} </h1>
    </div>

    <div class="text-right mr-5">
        <figure>
            <img src="{{stock.logo_url.to_string(index=False)}}" alt="">
        </figure>
    </div>
    
    <br>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th scope="row">Ticket </th>
                <td>{{ticket|upper}}</td>

            </tr>
            <tr>
                <th scope="row">Sector</th>
                <td>{{stock.sector.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">CurrentPrice</th>
                <td>{{stock.currentPrice.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">Ebitda</th>
                <td>{{stock.ebitda.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">Beta</th>
                <td>{{stock.beta.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">MarketCap</th>
                <td>{{stock.marketCap.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">TotalCash</th>
                <td>{{stock.totalCash.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">TotalDebt</th>
                <td>{{stock.totalDebt.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">Yield</th>
                <td>{{stock.yield.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">YtdReturn</th>
                <td>{{stock.ytdReturn.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">DividendYield</th>
                <td>{{stock.dividendYield.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">TotalDebt</th>
                <td>{{stock.totalDebt.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">Category</th>
                <td>{{stock.category.to_string(index=False)}}</td>
            </tr>
            <tr>
                <th scope="row">DividendRate</th>
                <td>{{stock.dividendRate.to_string(index=False)}}</td>
            </tr>
            
        </tbody>
    </table>

</div>

{% if graphic != None %}
<img src="data:image/png;base64,{{ graphic }}">
{% endif %}
<br><br><br><br><br><br><br><br><br><br>
<br><br>
{% endblock %}

quantAPP/templates/dashboard/wallet_form.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "components/base.html" %}

{% block page_body %}
<div class="content-section">

    {{ utils.flashed_messages() }}
    <br />
    <div class="center form-login">
        <h2>  Adicionar Posição</h2>
        <br/>
        {{ wtf.quick_form(form) }}
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br>
<br><br>
{% endblock %}